-- MySQL Script generated by MySQL Workbench
-- ter 19 dez 2017 00:37:26 -03
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema hibernate
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema hibernate
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `hibernate` DEFAULT CHARACTER SET utf8mb4 ;
USE `hibernate` ;

-- -----------------------------------------------------
-- Table `hibernate`.`Cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hibernate`.`Cliente` (
  `idcliente` INT(11) NOT NULL AUTO_INCREMENT,
  `nascimento` VARCHAR(255) NULL DEFAULT NULL,
  `nomecliente` VARCHAR(255) NULL DEFAULT NULL,
  `telefone` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`idcliente`))
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `hibernate`.`Produto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hibernate`.`Produto` (
  `idproduto` INT(11) NOT NULL AUTO_INCREMENT,
  `nomeproduto` VARCHAR(255) NULL DEFAULT NULL,
  `valorproduto` DOUBLE NOT NULL,
  PRIMARY KEY (`idproduto`))
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `hibernate`.`Vendedor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hibernate`.`Vendedor` (
  `idnomevendendor` INT(11) NOT NULL AUTO_INCREMENT,
  `nomevendedor` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`idnomevendendor`))
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `hibernate`.`Vendidos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hibernate`.`Vendidos` (
  `idvendidos` INT(11) NOT NULL AUTO_INCREMENT,
  `idcliente` INT(11) NOT NULL,
  `idproduto` INT(11) NOT NULL,
  `idnomevendendor` INT(11) NOT NULL,
  PRIMARY KEY (`idvendidos`),
  INDEX `FK_4hjft2t0s4j16ga955his43j` (`idcliente` ASC),
  INDEX `FK_nhketfcryi8b9oy1uusvyatw0` (`idproduto` ASC),
  INDEX `FK_b7py3shcskfw0x9gcxm0nj21y` (`idnomevendendor` ASC),
  CONSTRAINT `FK_4hjft2t0s4j16ga955his43j`
    FOREIGN KEY (`idcliente`)
    REFERENCES `hibernate`.`Cliente` (`idcliente`),
  CONSTRAINT `FK_b7py3shcskfw0x9gcxm0nj21y`
    FOREIGN KEY (`idnomevendendor`)
    REFERENCES `hibernate`.`Vendedor` (`idnomevendendor`),
  CONSTRAINT `FK_nhketfcryi8b9oy1uusvyatw0`
    FOREIGN KEY (`idproduto`)
    REFERENCES `hibernate`.`Produto` (`idproduto`))
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8mb4;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
